export const DIGITAL_HEADERS = [
  'Comercial',
  'Cliente',
  'Anunciante',
  'Producto',
  'Cadena',
  'Periodo Id',
  'Periodo',
  'Artículo',
  'Nº Centros',
  'Nº Soportes',
  'Campaña',
  'Línea campaña',
  'Fecha Fijación',
  'Fecha Retirada',
  'Tipo Fijación',
  'Observaciones Fijación',
  'Observaciones Almacen',
  'Contrato Enviado',
  'Contrato Recibido',
  'Produce ISM/Cliente',
  'Creatividad Repartida',
  'Escandallos Repartidos',
  'Orden de Trabajo Generada',
  'Creatividad Id',
  'Creatividad Desc.',
  'Creativitad Título',
  'Creatividad Estado',
  'Material',
  'Total Unidades Material',
  'Fecha Material',
  'Proveedor',
  'Número Pedido',
  'Unidades Pedido',
  'Fecha Pedido',
  'Producción',
  'Cantidades Enviadas',
  'Número Albarán',
  'Unidades Albarán',
  'Fecha Albarán',
] as const;
export const MINIMUM_HEADERS = [
  'Cadena',
  'Periodo Id',
  'Periodo',
  'Artículo',
  'Campaña',
  'Línea campaña',
  'Fecha Fijación',
  'Fecha Retirada',
  'Tipo Fijación',
  'Creatividad Id',
  'Nº Centros',
  'Nº Soportes',
] as const;
